# Generated by Django 3.2.8 on 2021-10-31 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipesapp', '0004_delete_recipeingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
