# Generated by Django 3.2.8 on 2021-11-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesapp', '0006_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='title_ingredient',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название ингридиента'),
        ),
    ]
